{{- if .Values.daggerCloudToken }}
apiVersion: v1
kind: Secret
metadata:
  name: dagger-cloud-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dagger-runners.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.daggerCloudToken | b64enc }}
{{- end }}
